---
# ============================================================
#                       Role: proton_suite
# ============================================================

- name: "Block: Install proton_suite Ansible Role"
  become: true
  vars:
    _proton_suite_should_install_proton_bridge: "{{ proton_suite_should_install_proton_bridge | bool }}"
  block:

    - name: Gather Installed Package Facts
      ansible.builtin.package_facts:
        manager: apt

    # ============================================================

    - name: "-------> Install Proton Bridge Tasks"
      include_tasks: ./proton-bridge.yaml
      # TODO: Run Molecule converge twice to see what the actual fact path is
      # when: >
      #   ansible_facts.packages.proton_bridge[0].version | default("0") == 0
      #   and
      #   _proton_suite_should_install_proton_bridge

  rescue:

    - name: "ERROR: Failed to install proton_suite"
      ansible.builtin.debug:
        msg: "ERROR: Failed to install proton_suite"

    - name: "Error detected! Stopping Playbook :-("
      ansible.builtin.fail:
        msg: "Error detected! Stopping Playbook :-("
