---
- name: Converge
  hosts:
    - all
  become: true
  gather_facts: false


  tasks:

    - name: "Converge - Scenario: Test Proton Bridge Install"
      ansible.builtin.include_role:
        name: "aaronvonawesome.proton_suite"
      vars:
        proton_suite_should_install_proton_bridge: true
